esphome:
  name: pflanzen_waechter
  friendly_name: Pflanzen Wächter
  comment: 18650-Battery Power Plant Watcher
  project: 
    name: "Dominic Hahn.Pflanzen Wache"
    version: "1.2.0"


esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: "W0M6rgMAibvI7KK279fyoL8OeUdxKH6uVB5sVFf6yNU="

ota:
  - platform: esphome
    password: "7fe1fe79ac546290d9237156463e0f44"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.104
    gateway: 192.168.0.1
    subnet: 255.255.255.0

web_server:
  port: 80
  version: 3


sensor:
  - platform: adc
    pin: VCC
    id: "VCC"
    name: Spannung
    device_class: voltage
    filters: 
      - multiply: 1.55
          

    
  - platform: template
    name: "18650 Battery"
    lambda: return id(VCC).state;
    device_class: battery
    accuracy_decimals: 0
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
         method: exact
         datapoints:
          - 0.00 -> 0.0
          - 3.30 -> 7.0
          - 3.39 -> 15.0
          - 3.50 -> 25.0
          - 3.75 -> 50.0
          - 3.90 -> 80.0
          - 4.11 -> 95.0
          - 4.20 -> 100.0
      - lambda: |-
          if (x <= 100) {
            return x;
          } else {
            return 100;
          }
          if (x <0) {
            return 0;
          }


  - platform: uptime
    type: seconds
    name: uptime


  - platform: dht
    pin: 14
    temperature: 
      name: "Temperatur"
    humidity: 
      name: "Luftfeuchtigkeit"
    update_interval: 10s
    model: DHT11

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    internal: True
    id: wifi_signal_db
    update_interval: 10s

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: adc
    pin: 17
    name: "Boden Feuchtigkeit"
    update_interval: 20s
    unit_of_measurement: "%"
    device_class: moisture
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

button:
  - platform: restart
    name: Reboot